# Autogenerated by devscripts/update-version.py

__version__ = '2025.12.26'

RELEASE_GIT_HEAD = '7a52ff29d86efc8f3adeba977b2009ce40b8e52e'

VARIANT = 'ngallo-fork'

UPDATE_HINT = None

CHANNEL = 'stable'

ORIGIN = 'yt-dlp/yt-dlp'

_pkg_version = '2025.12.08'
